### PR TITLE
Prepare for Prod

### LINKED ISSUE #1: Prepare for production
The project needs to be prepared for production. This means that build scripts need to be setup so the code is ready to be deployed.
For now, we can simply have a static web page that connects to the API. This will even allow us to use free hosting like Github Pages.

### PR DESCRIPTION
**Pull request by lopis**
- [x] Create separate webpack configs for dev and prod
- [x] Enable minification (webpack mode=prod)
- [x] Improve tree shaking of MaterialUI (see discussion in #1)
- [x] Prepare build for deployment, including `index.html` and assets.
- [x] Setup github pages to serve dist (maybe automate?)

Fixes #1

### CODE REVIEW

**Comment by kimamov** [comment]
I already added the default "deploy to github pages" action (only a working build script was missing).
I would suggest to run it on push to master and merge into master.
Maybe we can add some kind of branch preview later.

**Comment by lopis** [comment]
Oh, I missed that. I might cherry pick the `yml` into this PR then.

**Comment by lopis** [comment]
Ok, that should be it. Following your `yml`, I enabled github pages to deploy the branch `gh-pages`. That should be it,

**Review by kimamov — APPROVED** [review]

**Comment by lopis** [comment]
https://lopis.github.io/job-board/ It works! 🎉

**Comment by kimamov** [comment]
> https://lopis.github.io/job-board/ It works! 🎉

ya but client side routing is broken... there used be an easy fix for that but seems like its an even bigger shit show these days.
Think the easiest fix now is this: https://github.com/rafgraph/spa-github-pages

**Comment by lopis** [comment]
Hm, makes sense. We could use query parameters as routes for now and then move back to normal routes. But that solution using a custom 404 page is pretty ingenious!

**Comment by kimamov** [comment]
Well you can always just use Hash Router but was never a fan of it...

**Pull request merged**
