### PR TITLE
Remove package-lock

### PR DESCRIPTION
**Pull request by lopis**
We are using yarn.lock. We don't need packge-lock.json.

### CODE REVIEW

**Comment by lopis** [comment]
@all-contributors please add @lopis for code

**Comment by lopis** [comment]
Sorry for the spam...
@all-contributors please add @kantimam for code

**Review by kimamov — DISMISSED** [review]

**Comment by lopis** [comment]
@all-contributors please add @kantimam for review

**Comment by lopis** [comment]
@kantimam could you approve again? Your review was dismissed after i resolved some conflicts.

**Review by kimamov — APPROVED** [review]

**Pull request merged**
